### PR TITLE
Add C++ Implementation of Problem 4

### PR DESCRIPTION
**Pull request by jDerp**

### CODE REVIEW

**Review by yafiwebdev — CHANGES_REQUESTED** [review]
Hey, nice, but please consider the following:
- Add some line spacing (like under include, namespace, and between the two functions)
- More importantly, please make the function dynamic, i.e. not only for number 3, allow for a variable to be set, or passed through a function call, to try multiple results.

Thanks!

**Comment by jDerp** [comment]
Fixed requested changes

**Review by yafiwebdev — CHANGES_REQUESTED** [review]
Great, just find more descriptive variable names other than upbnd and lobnd then we can merge.

Thank you for the quick response!

**Review by yafiwebdev — CHANGES_REQUESTED** [review]
Brilliant!
I know I'm being a pain, but the code gives no output for digit = 4, I'd say this is because of 'int'?
I don't code in C++, but I guess some variables have to be 'long' here if I'm not mistaken.

Looking forward to the change, then we can directly merge the PR
Thanks again!

**Review by yafiwebdev — APPROVED** [review]
Terrific, thank you!
Merging...

I look forward to more solutions from you!

**Pull request merged**
