### PR TITLE
002-even-fibonacci-numbers.java #10

### PR DESCRIPTION
**Pull request by droidttk**
Java-based solution for problem 002 in Project Euler [Problem-2](https://projecteuler.net/problem=2)

### CODE REVIEW

**Review by yafiwebdev — CHANGES_REQUESTED** [review]
It works great, but I implore you guys to comment your code a bit, this is one of the only two rules. I've solved the issue myself and got confused with your b, d and d, haha.
Try to think of others reading your code..

Looking forward to the changes to merge your PR
Keep up the good work!

**Comment by droidttk** [comment]
@yafiwebdev Updated the PR based on your comments. Please review 🙇

**Review by yafiwebdev — APPROVED** [review]
Again, terrific work!

I see that you can work with Groovy, I'm not that familiar with it, do you think it's a suitable language for algorithms? If yes, then I'd be glad to add issues for it, would be more glad if you would solve them as well 🥇

**Comment by droidttk** [comment]
@yafiwebdev Thanks!
Yes, of course, I can work with groovy and it's suitable for algorithms. Let's add a couple of issues, I'll solve and work on them!

**Comment by yafiwebdev** [comment]
> @yafiwebdev Thanks!
> 
> Yes, of course, I can work with groovy and it's suitable for algorithms. Let's add a couple of issues, I'll solve and work on them!

Terrific! I will add some and assign you a couple.

**Comment by yafiwebdev** [comment]
@droidttk Done, check the issues and do the ones you like first. 
😀

**Pull request merged**
