### PR TITLE
001 sum multiples 3 and 5 in c#

### PR DESCRIPTION
**Pull request by dmodena**
I just created solution for problem 001 in C#. Related to issue #17

### CODE REVIEW

**Comment by dmodena** [comment]
You may need to add **hacktoberfest** and **hacktoberfest2020** topics to the repository in order for the Pull Requests to count

**Review by yafiwebdev — CHANGES_REQUESTED** [review]
It's almost done, just make sure you also loop through the number just before the limit, it's a common slip with loops, haha.
Expected: 233168
Received: 232169

Fix it quickly and let me merge your PR.

**Comment by dmodena** [comment]
@yafiwebdev Thank you for pointing that out! I just fixed the iteration in a new commit.

**Review by yafiwebdev — APPROVED** [review]
Added hacktoberfest topic, it should work, let me know.

**Pull request merged**
