### PR TITLE
Solve 001 Dart

### LINKED ISSUE #45: Solve Problem 1 in Dart

### PR DESCRIPTION
**Pull request by AlecsisDuarte**
Resolve #45 
[Euler 1](https://projecteuler.net/problem=1) in dart

### CODE REVIEW

**Review by yafiwebdev — CHANGES_REQUESTED** [review]
Hey, awesome that you're starting the Dart directory!
I have a question and a request building on that question.
Why not divide the five the same way you're dividing the three, namely (num % 5 == 0)
If that's not needed, then removing both functions would be nice, since each one would have one statement only, although it might be often clearer, but here it's really simple and a short comment would suffice, and generally, this first problem is quite easy.

Thank you for contributing and looking forward to your reply/changes

**Comment by AlecsisDuarte** [comment]
That's a good idea! I mainly started with the given logic around the isDivisibleByFive function because I thought a MOD 10 would be less cpu intensive than MOD 5 (ax CPUs do some multiplications internally), but so far I haven't found any reference/articles, so yeah, I'm also on your side on this one.

Thanks for the suggestions!!

**Comment by yafiwebdev** [comment]
@AlecsisDuarte 
Great! Looking forward to your changes to merge them.
Thank you again

**Comment by AlecsisDuarte** [comment]
@yafiwebdev 
Here are the changes, please have a look

**Review by yafiwebdev — APPROVED** [review]
Very concise now, thanks!

Looking forwards to more Dart (or other languages) solutions from you!

**Pull request merged**
