### PR TITLE
Add problem 7 solution in Python

### PR DESCRIPTION
**Pull request by adil659**

### CODE REVIEW

**Comment by yafiwebdev** [comment]
Hey, thank you for your contribution, but no Python solutions are needed, sorry!

**Comment by adil659** [comment]
Oh really.. how come..?

**Comment by adil659** [comment]
I'd appreciate if you'd accept it due to hacktoberfest...

**Comment by yafiwebdev** [comment]
@adil659 
This is my personal repository, and the JS/PHP/Pythons are all mine.
I started creating issues for other languages to help others win in Hacktoberfest, then it suddenly grew quite rapidly °o°

Really sorry, and thank you for your effort and time.

**Comment by adil659** [comment]
Ok, thanks

**Pull request closed without merging**
