### PR TITLE
Created 006diff_of_sum_and_squares.go

### PR DESCRIPTION
**Pull request by Error404m**
Solved problem number no 06 ( #28 ) in GO lang .

### CODE REVIEW

**Review by yafiwebdev — CHANGES_REQUESTED** [review]
Looks good! But please follow the file naming convention (see other folders)

Fix so that I can merge your PR.
Keep up the great work!

**Comment by Error404m** [comment]
Thanks a lot .....

**Comment by yafiwebdev** [comment]
> Thanks a lot .....

You're welcome, can you see the PR on your Hacktoberfest profile? @Error404m

**Comment by Error404m** [comment]
Yes sir

**Pull request merged**
