### PR TITLE
solve 9 ruby

### PR DESCRIPTION
**Pull request by StephenHogsten**

### CODE REVIEW

**Review by yafiwebdev — CHANGES_REQUESTED** [review]
This doesn't seem to be returning the correct result. Please make sure it's doing what the problem description requires.
Also, it would be nice to add some comments and make it clear where the input is, by passing it into a function call or setting it into a variable.

Thanks!

**Comment by StephenHogsten** [comment]
Sorry, I switched the output for debugging and forgot to switch it back.

I added a couple comments.  And made an input param - it will find the product of the first valid triple if one exists with that sum

**Review by yafiwebdev — COMMENTED** [review]
That's great, just a question before we merge.
I haven't solved this myself yet, but I remember seeing the result of some other contributor being the three numbers (49920, 55080, 60000) for the input(sum in your case) of 120
Your code is returning the first one only. Could be improved to consider all three and not only the first one?

I'm probably being annoying, but bear with me, just wanna have quite decent and helpful solutions for others to benefit from the most!

Thanks again!

**Comment by StephenHogsten** [comment]
It makes sense for debugging understanding.  I left it originally out b/c for the stated problem you just need the one so you can quit earlier.

Thanks for reviewing so quickly.  

Unrelated to this PR - are you planning on going up to 100 eventually?  Are you interested in including other languages like haskell?

**Comment by yafiwebdev** [comment]
> Unrelated to this PR - are you planning on going up to 100 eventually? Are you interested in including other languages like Haskell?

Hey, as for the 100, absolutely, I'm planning to at least finish the first 100 problems in three programming languages.

As for other languages, I'm always happy to add more! A few days ago I was doing it alone in three programming languages only, now you can see how it's grown!
So if you like to code in Haskell, by all means, feel free to create a folder and add the first problem, then I can add some issues for it.

I'd be really glad if you continue to provide nice solutions to help reach the 100th challenge in all these languages

**Review by yafiwebdev — APPROVED** [review]
Brilliant, works perfectly!
Thank you for your effort!

**Pull request merged**
