### PR TITLE
Created 001-multiples-of-3-and-5.java

### LINKED ISSUE #9: Solve Problem 1 in Java

### PR DESCRIPTION
**Pull request by Ares358**
Java program to calculate the solution for [Project Euler problem 1](https://projecteuler.net/problem=1) .
Closes #9

### CODE REVIEW

**Review by yafiwebdev — CHANGES_REQUESTED** [review]
This code is pretty slow, you only need one loop, not 3, try another approach, you can simply check if a number is divisible by 3 or 5
Keep up the momentum!

**Comment by Ares358** [comment]
Modified the program to check for multiples within a single loop as advised. Please review.

**Review by yafiwebdev — CHANGES_REQUESTED** [review]
Looks great! Just a quick edit and we can merge it, please use a parameter for the multiples and use it instead of only the number 1000

Keep it up ^_^

**Comment by Ares358** [comment]
Reasonable change. Thanks for the feedback. Updated the program!

**Review by yafiwebdev — APPROVED** [review]
Great!
Let me know if you see the PR on your hacktoberfest profile

**Pull request merged**
