### PR TITLE
Added problem 034 in C

### PR DESCRIPTION
**Pull request by yokesh004**

### CODE REVIEW

**Review by yafiwebdev — CHANGES_REQUESTED** [review]
This doesn't seem to be a solution to that problem, please read the description carefully. Thanks!

**Comment by yokesh004** [comment]
Sorry for that fault.  Now the error has been fixed.  Please have a look

**Review by yafiwebdev — CHANGES_REQUESTED** [review]
You need to also return the numbers, not just the sum.

**Comment by yokesh004** [comment]
I made the changes you asked for.  Please check that.

**Review by yafiwebdev — APPROVED** [review]
I added the missing closing curly brace of the main() in the C++ solution.

Thank you very much for the comments, I hope they help a lot of people!

Really looking forward to more terrific solutions from you!

**Pull request merged**
