### PR TITLE
Problem 1 solved in F# and Kotlin - Problem 2 solved in F#, Dart, Kotlin and Problem 5 solved in Java

### PR DESCRIPTION
**Pull request by kriitoboni**

### CODE REVIEW

**Comment by kriitoboni** [comment]
Solved #49 and #59

**Comment by kriitoboni** [comment]
Solved #60 and #13

**Review by yafiwebdev — CHANGES_REQUESTED** [review]
Hey, thank you for contributing, really glad to see even more new languages, but there are issues in the code:
- In the F# solution the compiler is complaining about indentation problems with tabs
-  As for Kotlin, I'm getting **Type mismatch: inferred type is Int but Unit was expected** among other stuff, have you checked the code before committing?

Thanks again

**Comment by kriitoboni** [comment]
Solved #46 and #50

**Comment by yafiwebdev** [comment]
Oh, quite a lot of solutions at once!
It would have been better to separate them, now we'd have to go through them all before merging.
Anyway, please check the issues I mentioned before I review the other files.

Also, please change the filenames to match the convention on the repo, check any folder for reference

Thank you!

**Comment by kriitoboni** [comment]
> Oh, quite a lot of solutions at once!
> It would have been better to separate them, now we'd have to go through them all before merging.
> Anyway, please check the issues I mentioned before I review the other files.
> 
> Also, please change the filenames to match the convention on the repo, check any folder for reference
> 
> Thank you!

Yes, I'm checking your reviews. Thank you for your comments.

**Pull request closed without merging**
