### PR TITLE
solves problem 13 in c++

### PR DESCRIPTION
**Pull request by phoffmeister**
solves #159

### CODE REVIEW

**Review by yafiwebdev — CHANGES_REQUESTED** [review]
Great, but I have a small request; please add another function that returns the 'input' and define it at the end so that the solution starts at the top of the file without having to scroll that much.

Thank you!

**Comment by phoffmeister** [comment]
All right. Im on it :+1:

**Comment by phoffmeister** [comment]
@yafiwebdev what do you think?

**Review by yafiwebdev — APPROVED** [review]
Terrific, thank you for being so responsive!

Look forward to more solutions from you!

**Pull request merged**
